Procedure: "Flanker task"

# * EEG
Send_EEG_trigg: False
Actiview_reminder: True

# * view parameters
Screen_color: "black"
Text_color: "white"
Text_size: 0.04
Flanker_size: 0.092
Text_font: "Arial"

# * flanker parameters
Fixation: "+.png"
Arrow_left: "bracket_left.png"
Arrow_right: "bracket_right.png"
Fixation_size: 0.04
Flanker_size: [0.05, 0.05]
Flanker_spacing: 0.04
Orientation: "horizontal"

# * cue definition
Show_cues: True
Cues: [5, 100]
Cue_size: 0.081  # 2 degrees
Cue_pos: [0.0, 0.004]

# * times
Cue_show_time: [2.000, 2.000, 0.100]
Empty_screen_after_cue_show_time: [0.500, 0.800, 0.100]
Target_show_time: [0.200, 0.200, 0.100]
Blank_screen_for_response_show_time: [1.700, 2.300, 0.100]


# * experiment structure
Experiment_blocks: [
    {type: break, file_name: instruction.txt},
    {type: training, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},
    {type: break, file_name: end_training.txt},
    {type: rest, duration: 5, info_duration: 4, file_name: rest_info.txt},

    {type: experiment, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},

    {type: break, file_name: end.txt}]
