Procedure: "Flanker task"

# * EEG
Send_EEG_trigg: False
Actiview_reminder: True

# * view parameters
Screen_color: "black"
Text_size: 0.04
Text_font: "Arial"
Text_color: "white"
Fixation_size: 0.087
# 3/360*2*3.14*50/30 / 6.4   (6.4 is the proportion of text width to height)
Target_size: 0.0136
# needs to be calibrated when Target_size or Fixation_size is changed
Fixation_offset: 0.008

# * times
Target_show_time: [4.200, 4.200, 0.100]
Blank_screen_for_response_show_time: [2.000, 2.400, 0.100]

# * experiment parameters
Response_key: {
    "red": "l",
    "green": "r",
}
Response_instruction: |
    Jeśli KOLOR CZCIONKI jest CZERWONY:
    naciśnij LEWY przycisk myszy

    Jeśli KOLOR CZCIONKI jest ZIELONY:
    naciśnij PRAWY przycisk myszy



# * experiment structure
Experiment_blocks: [
    # {type: break, num: 4, file_name: break_template.txt},
    {type: break, file_name: greet.txt},
    {type: break, file_name: explain1.txt},
    {type: break, file_name: explain2.txt},
    {type: training, number_of_trials: 6},
    {type: break, file_name: trening2.txt},
    {type: training, number_of_trials: 6},
    {type: break, file_name: end_training.txt},
    {type: rest, duration: 5, info_duration: 4, file_name: rest_info.txt},

    {type: experiment, number_of_trials: 6},
    {type: break, num: 1, file_name: break_template.txt},
    {type: experiment, number_of_trials: 6},

    {type: break, file_name: end.txt}]
